BlogApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('addPost', views.addPost, name='add-Post'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Post(models.Model):
    name = models.CharField('Author Name', max_length=120)
    title = models.CharField(max_length=120, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    # author = models.ForeignKey(
    #     User, on_delete=models.CASCADE, related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    # Its for meta data '-' define descending order, by doing this post published recently will appear first
    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

blog/forms.py
from django.forms import ModelForm, widgets
from django import forms
from .models import Post

# Create a POST form


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('name', 'title', 'content', 'status')
        labels = {
            'name': '',
            'title': '',
            'content': '',
        }

        STATUS = [(0,'Draft'),(1,'Publish')]

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your name'}),

            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the title'}),

            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'This is your canvas of imagination'}),

            'status': forms.Select(choices=STATUS),
        }

blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Post
from .forms import PostForm
from django.http import HttpResponseRedirect
# Create your views here.


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'


def addPost(request):
    submitted = False
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/addPost?submitted=True')

    else:
        form = PostForm
        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'addPost.html', {'form': form, 'submitted': submitted})

templates/addPost.html
{% extends "base.html" %}

{% block content %}
<style>
    body{
        margin-top: 80px;
    }
    .post-heading{
       color: #66d6a2 !important;
    }
    h3{
        color: white !important;
        font-size: large !important;
    }
</style>

    <h1 class="post-heading">Create your post here...</h1>
    <br/>
    <div class="container">
    {% if submitted %}
        <h3>Your post has been submitted successfully!!</h3>
    {% else %}

    <form action="" method=POST>
    {% csrf_token %}

    <center>
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-success">
    </center>
    
    </form>
    {% endif %}
    </div>
{% endblock content %}

templates/base.html
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog|App</title>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>

        <style>
            body {
                font-family: "Roboto", sans-serif;
                font-size: 17px;
                background-color: #0d0d0d;
            }
        
            .shadow {
                box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
            }
        
            .btn-danger {
                color: #fff;
                background-color: #f00000;
                border-color: #dc281e;
            }
        
            .masthead {
                background: #66d6a2;
                color: black;
                height: auto;
                padding-bottom: 15px;
                padding-top: 10px;
            }

            .btn{
                background-color: #66d6a2 !important;
                border: none !important;
                font-weight: 600;
            }
        </style>


    <nav class="navbar navbar-light bg-light fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href={% url 'home' %}><strong>Bloogs</strong></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
                aria-controls="offcanvasNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Bloogs</h5>
                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href={% url 'home' %}>Home</a>
                            <a class="nav-link active" aria-current="page" href={% url 'add-Post' %}>Create</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    {% block content %}
    <!-- content goes here -->
    {% endblock content %}
    
    
    <!-- footer -->
    <div class="card text-center">
        <div class="card-body">
            <h5 class="card-title">Made with django by Simp0la</h5>
            <p class="card-text">A basic django web application made for creating and publishing posts made by users.</p>
            <a href={% url 'home' %} class="btn btn-primary">Go to home</a>
        </div>
    </div> 


    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}


<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #0d0d0d;
        margin-top: 80px;
    }

    .head_text {
        color: #0d0d0d;
    }
    .masthead{
        color: #0d0d0d !important;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3"> Your thoughts are precious </h3>
                    <p class="text-light">Share them and enlighten all...
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">
        <!-- blog enteries -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card card-post mb-4">
                <div class="card-body">
                    <h2 class="card-title">
                        {{ post.title }}
                    </h2>
                    <p class="card-text text-muted h6">
                        {{ post.name }}
                    </p>
                    <p class="card-text"> {{ post.content|slice:":200" }} </p>
                    <a href="{% url 'post_detail' post.slug %}" class="btn btn-read btn-primary">read more &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        
        {% block sidebar %}
        
        <style>
            .card-title{
                color: #66d6a2 !important;
            }

            .card-post{
                border-radius: 20px !important;
                transition: 0.3s all ease-in-out;
            }

            .card-post:hover{
                scale: 1.05;
                transition: 0.3s all ease-in-out;
            }
            .btn-read{
                border-radius: 10px !important;
                text-transform: uppercase;
                color: #0d0d0d;
            }
            .card-about{
                border: 6px solid white !important;
                border-radius:  10px !important;
                background-color: #66d6a2;
                

            }
            
        </style>
        
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4 float-right ">
            <div class="card card-about my-4">
                <h5 class="card-header">About Us</h5>
                <div class="card-body">
                    <p class="card-text">This is a normal blog website where you can post your blogs anytime and feel free to
                        reach us... </p>
                </div>
            </div>
        </div>
        
        {% endblock sidebar %}
    </div>
</div>

{% endblock %}

templates/post_detail.html
{% extends "base.html" %}

{% block content %}


<style>

body{
    margin-top: 80px;
}

</style>

<div class="container">
    <div class="row">
        <div class="col-md-8 mb-4 mt-3 left top">
            <div class="card-body">
                <h1>{% block title %}
                    {{ object.title }}
                    {% endblock title %}
                </h1>
                <p class="text-muted">
                    {{ post.author }} | {{ post.created_on }}
                </p>
                <p class="card-text">
                    {{ object.content | safe }}
                </p>
            </div>
        </div>
        {% block sidebar %}

        <style>
            .card {
                box-shadow: 0 16px 48px #e3373b;
            }
        </style>
        
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4 float-right ">
            <div class="card my-4">
                <h5 class="card-header">About Us</h5>
                <div class="card-body">
                    <p class="card-text">This is a normal blog website where you can post your blogs anytime and feel free to reach us... </p>
                </div>
            </div>
        </div>
        {% endblock sidebar %}
    </div>
</div>

{% endblock content %}